/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ares_x_jnidemo_NdkTools */

#ifndef _Included_com_ares_x_jnidemo_NdkTools
#define _Included_com_ares_x_jnidemo_NdkTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ares_x_jnidemo_NdkTools
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ares_x_1jnidemo_NdkTools_getString
  (JNIEnv *JNIEnv, jclass jczz){
    return (*JNIEnv)->NewStringUTF(JNIEnv,"调用JNI成功!");
  }

#ifdef __cplusplus
}
#endif
#endif
